### ISSUE TITLE
Mobile Opera

### ISSUE THREAD

**Issue by MacKenzieRose** [cmvolden/ecommerce-pattern-library#10]
Hi @cmvolden :)

I know you said you weren't ready for yours to be tested yet; I have a lab from 5–7 today, so I'll come back to test yours then :)

MacKenzie

**Comment by cmvolden** [comment]
Thanks @MacKenzieRose ! I'm all done my homepage now. Or at least moving on to the next thing.

**Comment by MacKenzieRose** [comment]
Then I'll test it now :)

**Comment by MacKenzieRose** [comment]
It's looking pretty spiffy! :)

The only things I caught going through; `sometimes your icons get slightly cropped by surrounding elements` (see below):

![IMG_0631](https://user-images.githubusercontent.com/19557909/79620395-bc176900-80dd-11ea-9dcc-00771dc8ce99.png)

The other thing is that `SALE gets pushed to its own line at small screen sizes` (this only occurs on portrait mode, so we're looking at just around ~320 pixels/xs screen sizes):

![IMG_0632](https://user-images.githubusercontent.com/19557909/79620396-bcafff80-80dd-11ea-8173-2395bdc67902.png)

Your site brought me a lot of joy; I'm also really digging the font choices! :)
