### ISSUE TITLE
Targeting

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/ecommerce-pattern-library#2]
@thomasjbradley

I’m working on my pattern library trying to target things and I just can’t wrap my head around how to make my card look like my XD card since I’m not able to target elements. For example, my border colour is not changing to yellow.
<img width="1474" alt="Screenshot 2020-02-06 15 47 21" src="https://user-images.githubusercontent.com/43150501/73978353-28196c00-48fa-11ea-8b02-45473194215b.png">

**Comment by thomasjbradley** [comment]
I don’t see the `subscribe.html` file—has it been committed?

**Comment by cmvolden** [comment]
@thomasjbradley yes, it is now, sorry!

**Comment by thomasjbradley** [comment]
Looks like you got the border colour working..?

**Comment by cmvolden** [comment]
@thomasjbradley yes I think so. Oh, I'm sorry, I thought I had a part 2 to that email so was waiting for an answer instead of closing the issue. My bad! Thank you!
