### ISSUE TITLE
Grade for: Sharing code with layouts

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/ecommerce-pattern-library#3]
@thomasjbradley I've completed the assignment "Sharing code with layouts" from week 09.

![config-layouts](https://user-images.githubusercontent.com/43150501/77198394-45c31f00-6abd-11ea-8a92-37a0309d062b.png)
![products-layout](https://user-images.githubusercontent.com/43150501/77198398-465bb580-6abd-11ea-8e92-b31f3a12710f.png)
![default-layout](https://user-images.githubusercontent.com/43150501/77198401-46f44c00-6abd-11ea-88a5-ccf81cdd0fa9.png)

**Comment by thomasjbradley** [comment]
:sparkles:

**Comment by cmvolden** [comment]
Thanks!
