### ISSUE TITLE
Building pages with patterns

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/ecommerce-pattern-library#4]
Hi @thomasjbradley, I am working on creating the includes for my banner images, but am trying to apply it to my images instead of icons, and my brain is exploding trying to work it out. How does the include know to search for an image? I've added another image into my folder to be used (artist-1.jpg, and artist-2.jpg) I am lost..

**Comment by thomasjbradley** [comment]
In the `<img>` tag itself, in the `src`, we need to replace everything between the quotes with the `{{include}}` placeholder:
https://github.com/cmvolden/ecommerce-pattern-library/blob/master/_patterns/banners/main-banner.html#L2

```html
<img class="img-flex" src="{{include.image}}" alt="">
```

Then when you use the pattern:
https://github.com/cmvolden/ecommerce-pattern-library/blob/master/index.html#L5
You’d add a new attribute named `image`:

```liquid
{% pattern banners/main-banner image="/images/artist-2.jpg" heading="They …
```

**Comment by cmvolden** [comment]
Ah, okay I understand. Thank you!
