### ISSUE TITLE
Issue: Tweak & hide the button > Building pages with patterns

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/ecommerce-pattern-library#5]
Hi @thomasjbradley ,
I've been trying to get my button to do the hiding thing on my banner and seem to be missing something. Do you mind having a look?

_patterns/banners/main-banner.html

**Comment by thomasjbradley** [comment]
There’s a closing if-statement missing, above this line:
https://github.com/cmvolden/ecommerce-pattern-library/blob/master/_patterns/banners/main-banner.html#L10

```
{% endif %}
```

**Comment by cmvolden** [comment]
Ah, yes... thank you so much!
